<!DOCTYPE html>
<html style="font-size: 16px;">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="Calon Kandidat KetuaHimpunan Mahasiswa Program StudiHukum Pidana Islam Fakultas Syariah">
    <meta name="description" content="">
    <meta name="page_type" content="np-template-header-footer-from-plugin">
    <title>system</title>
    <link rel="stylesheet" href="nicepage.css" media="screen">
<link rel="stylesheet" href="system.css" media="screen">
    <script class="u-script" type="text/javascript" src="jquery.js" defer=""></script>
    <script class="u-script" type="text/javascript" src="nicepage.js" defer=""></script>
    <meta name="generator" content="Nicepage 3.7.1, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i">
    
    
    <script type="application/ld+json">{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": "",
		"url": "index.html"
}</script>
    <meta property="og:title" content="system">
    <meta property="og:type" content="website">
    <meta name="theme-color" content="#478ac9">
    <link rel="canonical" href="index.html">
    <meta property="og:url" content="index.html">
  </head>
  <body class="u-body u-overlap u-overlap-transparent"><header class="u-align-left u-clearfix u-header u-header" id="sec-ba2f"><div class="u-clearfix u-sheet u-sheet-1"></div></header>
    <section class="u-clearfix u-hidden-sm u-section-1" id="sec-642a">
      <img src="images/Presentation1-removebg.png" alt="" class="u-expanded-width u-image u-image-default u-image-1" data-image-width="1277" data-image-height="193">
      <h2 class="u-align-center u-text u-text-1"><b style="">Sistem Pemilihan Umum<br>&nbsp;Fakultas Syariah</b>
        <br>
      </h2>
      <img src="images/Logo-iain.png" alt="" class="u-image u-image-default u-preserve-proportions u-image-2" data-image-width="400" data-image-height="432">
      <img src="images/logoKPUMFASYA.png" alt="" class="u-image u-image-default u-preserve-proportions u-image-3" data-image-width="970" data-image-height="1600">
      <div class="u-border-2 u-border-grey-dark-1 u-container-style u-group u-shape-rectangle u-group-1">
        <div class="u-container-layout u-valign-middle u-container-layout-1">
          <h1 class="u-align-center u-text u-text-default u-text-2"><b>TERIMA KASIH TELAH MENGIKUTI PEMILU FASYA 2021</b>
          </h1>
        </div>
      </div>
    </section>
    
    
    <footer class="u-align-center u-clearfix u-footer u-grey-80 u-footer" id="sec-2515"><div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
        <p class="u-small-text u-text u-text-variant u-text-1">System Generated By KHL</p>
      </div></footer>
    <section class="u-backlink u-clearfix u-grey-80">
      <a class="u-link" href="https://nicepage.com/css-templates" target="_blank">
        <span>CSS Templates</span>
      </a>
      <p class="u-text">
        <span>created with</span>
      </p>
      <a class="u-link" href="https://nicepage.com/html-website-builder" target="_blank">
        <span>WYSIWYG HTML Editor</span>
      </a>. 
    </section>
  </body>
</html>